// languages.js
export const SUPPORTED_LANGUAGES = [
    { 
        name: "日本語", 
        code: "ja-JP",
        ui: {
            start: "録音開始",
            stop: "停止",
            copy: "📋 内容をコピー",
            organizeCopy: "📋 整理プロンプト付きでコピー",
            reset: "🗑️ 文字起こし内容を消去",
            confirmReset: "内容をクリアしますか？",
            copyDone: "完了！",
            organizePrompt: "以下は口述内容を音声認識させたものである。音声認識特有の誤字脱字を取り除き繰り返しやフィラー語を整理したうえで、議論の進展を整理せよ\n\n"
        }
    },
    { 
        name: "English", 
        code: "en-US",
        ui: {
            start: "Start Recording",
            stop: "Stop",
            copy: "📋 Copy Text",
            organizeCopy: "📋 Copy with organizing prompt",
            reset: "🗑️ Clear Transcription",
            confirmReset: "Are you sure you want to clear the text?",
            copyDone: "Done!",
            organizePrompt: "The following is a transcript generated by speech recognition. Remove recognition-specific typos and errors, eliminate repetitions and filler words, and then summarize the progress of the discussion.\n\n"
        }
    },
    { 
        name: "Español", 
        code: "es-ES",
        ui: {
            start: "Iniciar grabación",
            stop: "Detener",
            copy: "📋 Copiar texto",
            organizeCopy: "📋 Copiar con prompt de ordenamiento",
            reset: "🗑️ Borrar transcripción",
            confirmReset: "¿Estás seguro de que deseas borrar el texto?",
            copyDone: "¡Copiado!",
            organizePrompt: "Lo siguiente es una transcripción generada por reconocimiento de voz. Elimina errores tipográficos y errores propios del reconocimiento, suprima repeticiones y muletillas, y luego resume el progreso de la discusión.\n\n"
        }
    },
    { 
        name: "Français", 
        code: "fr-FR",
        ui: {
            start: "Démarrer l'enregistrement",
            stop: "Arrêter",
            copy: "📋 Copier le texte",
            organizeCopy: "📋 Copier avec prompt de tri",
            reset: "🗑️ Effacer la transcription",
            confirmReset: "Êtes-vous sûr de vouloir effacer le texte ?",
            copyDone: "Copié !",
            organizePrompt: "Ce qui suit est une transcription générée par la reconnaissance vocale. Supprimez les fautes et erreurs spécifiques à la reconnaissance, éliminez les répétitions et les mots de remplissage, puis résumez l'avancement de la discussion.\n\n"
        }
    },
    { 
        name: "中文", 
        code: "zh-CN",
        ui: {
            start: "开始录音",
            stop: "停止",
            copy: "📋 复制文本",
            organizeCopy: "📋 附整理提示复制",
            reset: "🗑️ 清除内容",
            confirmReset: "您確定要清除文字嗎？",
            copyDone: "完成！",
            organizePrompt: "以下内容为语音识别生成的转录。请去除识别特有的错字和错误，删去重复和填充词，并整理总结讨论的进展。\n\n"
        }
    }
];